// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdxLi-hb11nUSy80_JJ3IoST3IASyIdK4',
    appId: '1:563067731281:web:2a61a5deda5b2da5742770',
    messagingSenderId: '563067731281',
    projectId: 'inventory-management-6a18d',
    authDomain: 'inventory-management-6a18d.firebaseapp.com',
    databaseURL: 'https://inventory-management-6a18d-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-management-6a18d.firebasestorage.app',
    measurementId: 'G-ZKFY2GXV9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyRzy3N6LCPyWH5ESWYOdaXjlOWWjIflE',
    appId: '1:563067731281:android:a4e1df186e6e9078742770',
    messagingSenderId: '563067731281',
    projectId: 'inventory-management-6a18d',
    databaseURL: 'https://inventory-management-6a18d-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-management-6a18d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu7d2Ain6yJHRr4YBZpZICyUph7Fxaeic',
    appId: '1:563067731281:ios:999732566d3f1b20742770',
    messagingSenderId: '563067731281',
    projectId: 'inventory-management-6a18d',
    databaseURL: 'https://inventory-management-6a18d-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-management-6a18d.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu7d2Ain6yJHRr4YBZpZICyUph7Fxaeic',
    appId: '1:563067731281:ios:999732566d3f1b20742770',
    messagingSenderId: '563067731281',
    projectId: 'inventory-management-6a18d',
    databaseURL: 'https://inventory-management-6a18d-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-management-6a18d.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdxLi-hb11nUSy80_JJ3IoST3IASyIdK4',
    appId: '1:563067731281:web:4d31acc05b04b9ba742770',
    messagingSenderId: '563067731281',
    projectId: 'inventory-management-6a18d',
    authDomain: 'inventory-management-6a18d.firebaseapp.com',
    databaseURL: 'https://inventory-management-6a18d-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-management-6a18d.firebasestorage.app',
    measurementId: 'G-5N1Q2V4RDV',
  );
}
